/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  EntityModelAuthorityEntity,
  EntityModelAuthorityEntityFromJSON,
  EntityModelAuthorityEntityToJSON,
} from '../models';

export interface ExecuteSearchAuthorityentityGetRequest {
  name?: ExecuteSearchAuthorityentityGetNameEnum;
}

/**
 *
 */
export class AuthorityEntitySearchControllerApi extends runtime.BaseAPI {
  /**
   */
  async executeSearchAuthorityentityGetRaw(
    requestParameters: ExecuteSearchAuthorityentityGetRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<EntityModelAuthorityEntity>> {
    const queryParameters: any = {};

    if (requestParameters.name !== undefined) {
      queryParameters['name'] = requestParameters.name;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/authorityEntities/search/findByName`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelAuthorityEntityFromJSON(jsonValue));
  }

  /**
   */
  async executeSearchAuthorityentityGet(
    requestParameters: ExecuteSearchAuthorityentityGetRequest = {},
    initOverrides?: RequestInit,
  ): Promise<EntityModelAuthorityEntity> {
    const response = await this.executeSearchAuthorityentityGetRaw(requestParameters, initOverrides);
    return await response.value();
  }
}

/**
 * @export
 * @enum {string}
 */
export enum ExecuteSearchAuthorityentityGetNameEnum {
  OrdinaryUser = 'ORDINARY_USER',
  VideoCreator = 'VIDEO_CREATOR',
  Admin = 'ADMIN',
}
