/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
  CollectionModelEntityModelUserEntity,
  CollectionModelEntityModelUserEntityFromJSON,
  CollectionModelEntityModelUserEntityToJSON,
  EntityModelUserEntity,
  EntityModelUserEntityFromJSON,
  EntityModelUserEntityToJSON,
} from '../models';

export interface ExecuteSearchUserentityGetRequest {
  group?: string;
}

export interface ExecuteSearchUserentityGet1Request {
  username?: string;
}

/**
 *
 */
export class UserEntitySearchControllerApi extends runtime.BaseAPI {
  /**
   */
  async executeSearchUserentityGetRaw(
    requestParameters: ExecuteSearchUserentityGetRequest,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<CollectionModelEntityModelUserEntity>> {
    const queryParameters: any = {};

    if (requestParameters.group !== undefined) {
      queryParameters['group'] = requestParameters.group;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/users/search/findAllByGroup_Name`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CollectionModelEntityModelUserEntityFromJSON(jsonValue),
    );
  }

  /**
   */
  async executeSearchUserentityGet(
    requestParameters: ExecuteSearchUserentityGetRequest = {},
    initOverrides?: RequestInit,
  ): Promise<CollectionModelEntityModelUserEntity> {
    const response = await this.executeSearchUserentityGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async executeSearchUserentityGet1Raw(
    requestParameters: ExecuteSearchUserentityGet1Request,
    initOverrides?: RequestInit,
  ): Promise<runtime.ApiResponse<EntityModelUserEntity>> {
    const queryParameters: any = {};

    if (requestParameters.username !== undefined) {
      queryParameters['username'] = requestParameters.username;
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/users/search/findByUsername`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelUserEntityFromJSON(jsonValue));
  }

  /**
   */
  async executeSearchUserentityGet1(
    requestParameters: ExecuteSearchUserentityGet1Request = {},
    initOverrides?: RequestInit,
  ): Promise<EntityModelUserEntity> {
    const response = await this.executeSearchUserentityGet1Raw(requestParameters, initOverrides);
    return await response.value();
  }
}
