/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface AuthorityEntityResponse
 */
export interface AuthorityEntityResponse {
  /**
   *
   * @type {string}
   * @memberof AuthorityEntityResponse
   */
  name: AuthorityEntityResponseNameEnum;
  /**
   *
   * @type {number}
   * @memberof AuthorityEntityResponse
   */
  id?: number;
  /**
   *
   * @type {string}
   * @memberof AuthorityEntityResponse
   */
  authority: string;
}

/**
 * @export
 * @enum {string}
 */
export enum AuthorityEntityResponseNameEnum {
  OrdinaryUser = 'ORDINARY_USER',
  VideoCreator = 'VIDEO_CREATOR',
  Admin = 'ADMIN',
}

export function AuthorityEntityResponseFromJSON(json: any): AuthorityEntityResponse {
  return AuthorityEntityResponseFromJSONTyped(json, false);
}

export function AuthorityEntityResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorityEntityResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    id: !exists(json, 'id') ? undefined : json['id'],
    authority: json['authority'],
  };
}

export function AuthorityEntityResponseToJSON(value?: AuthorityEntityResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    id: value.id,
    authority: value.authority,
  };
}
