/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CollectionModelObjectEmbedded
 */
export interface CollectionModelObjectEmbedded {
  /**
   *
   * @type {Array<object>}
   * @memberof CollectionModelObjectEmbedded
   */
  objects?: Array<object>;
}

export function CollectionModelObjectEmbeddedFromJSON(json: any): CollectionModelObjectEmbedded {
  return CollectionModelObjectEmbeddedFromJSONTyped(json, false);
}

export function CollectionModelObjectEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CollectionModelObjectEmbedded {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    objects: !exists(json, 'objects') ? undefined : json['objects'],
  };
}

export function CollectionModelObjectEmbeddedToJSON(value?: CollectionModelObjectEmbedded | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    objects: value.objects,
  };
}
