/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  AuthorityEntityResponse,
  AuthorityEntityResponseFromJSON,
  AuthorityEntityResponseFromJSONTyped,
  AuthorityEntityResponseToJSON,
} from './AuthorityEntityResponse';

/**
 *
 * @export
 * @interface CollectionModelAuthorityEntityEmbedded
 */
export interface CollectionModelAuthorityEntityEmbedded {
  /**
   *
   * @type {Array<AuthorityEntityResponse>}
   * @memberof CollectionModelAuthorityEntityEmbedded
   */
  authorityEntities?: Array<AuthorityEntityResponse>;
}

export function CollectionModelAuthorityEntityEmbeddedFromJSON(json: any): CollectionModelAuthorityEntityEmbedded {
  return CollectionModelAuthorityEntityEmbeddedFromJSONTyped(json, false);
}

export function CollectionModelAuthorityEntityEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CollectionModelAuthorityEntityEmbedded {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    authorityEntities: !exists(json, 'authorityEntities')
      ? undefined
      : (json['authorityEntities'] as Array<any>).map(AuthorityEntityResponseFromJSON),
  };
}

export function CollectionModelAuthorityEntityEmbeddedToJSON(
  value?: CollectionModelAuthorityEntityEmbedded | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    authorityEntities:
      value.authorityEntities === undefined
        ? undefined
        : (value.authorityEntities as Array<any>).map(AuthorityEntityResponseToJSON),
  };
}
