/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  CollectionModelVideoEntityEmbedded,
  CollectionModelVideoEntityEmbeddedFromJSON,
  CollectionModelVideoEntityEmbeddedFromJSONTyped,
  CollectionModelVideoEntityEmbeddedToJSON,
} from './CollectionModelVideoEntityEmbedded';
import { Link, LinkFromJSON, LinkFromJSONTyped, LinkToJSON } from './Link';

/**
 *
 * @export
 * @interface CollectionModelVideoEntity
 */
export interface CollectionModelVideoEntity {
  /**
   *
   * @type {CollectionModelVideoEntityEmbedded}
   * @memberof CollectionModelVideoEntity
   */
  embedded?: CollectionModelVideoEntityEmbedded;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof CollectionModelVideoEntity
   */
  links?: { [key: string]: Link };
}

export function CollectionModelVideoEntityFromJSON(json: any): CollectionModelVideoEntity {
  return CollectionModelVideoEntityFromJSONTyped(json, false);
}

export function CollectionModelVideoEntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CollectionModelVideoEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    embedded: !exists(json, '_embedded') ? undefined : CollectionModelVideoEntityEmbeddedFromJSON(json['_embedded']),
    links: !exists(json, '_links') ? undefined : mapValues(json['_links'], LinkFromJSON),
  };
}

export function CollectionModelVideoEntityToJSON(value?: CollectionModelVideoEntity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    _embedded: CollectionModelVideoEntityEmbeddedToJSON(value.embedded),
    _links: value.links === undefined ? undefined : mapValues(value.links, LinkToJSON),
  };
}
