/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  UserGroupEntityResponse,
  UserGroupEntityResponseFromJSON,
  UserGroupEntityResponseFromJSONTyped,
  UserGroupEntityResponseToJSON,
} from './UserGroupEntityResponse';

/**
 *
 * @export
 * @interface CollectionModelUserGroupEntityEmbedded
 */
export interface CollectionModelUserGroupEntityEmbedded {
  /**
   *
   * @type {Array<UserGroupEntityResponse>}
   * @memberof CollectionModelUserGroupEntityEmbedded
   */
  userGroupEntities?: Array<UserGroupEntityResponse>;
}

export function CollectionModelUserGroupEntityEmbeddedFromJSON(json: any): CollectionModelUserGroupEntityEmbedded {
  return CollectionModelUserGroupEntityEmbeddedFromJSONTyped(json, false);
}

export function CollectionModelUserGroupEntityEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CollectionModelUserGroupEntityEmbedded {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userGroupEntities: !exists(json, 'userGroupEntities')
      ? undefined
      : (json['userGroupEntities'] as Array<any>).map(UserGroupEntityResponseFromJSON),
  };
}

export function CollectionModelUserGroupEntityEmbeddedToJSON(
  value?: CollectionModelUserGroupEntityEmbedded | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userGroupEntities:
      value.userGroupEntities === undefined
        ? undefined
        : (value.userGroupEntities as Array<any>).map(UserGroupEntityResponseToJSON),
  };
}
