/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  EntityModelUserGroupEntity,
  EntityModelUserGroupEntityFromJSON,
  EntityModelUserGroupEntityFromJSONTyped,
  EntityModelUserGroupEntityToJSON,
} from './EntityModelUserGroupEntity';

/**
 *
 * @export
 * @interface CollectionModelEntityModelUserGroupEntityEmbedded
 */
export interface CollectionModelEntityModelUserGroupEntityEmbedded {
  /**
   *
   * @type {Array<EntityModelUserGroupEntity>}
   * @memberof CollectionModelEntityModelUserGroupEntityEmbedded
   */
  userGroupEntities?: Array<EntityModelUserGroupEntity>;
}

export function CollectionModelEntityModelUserGroupEntityEmbeddedFromJSON(
  json: any,
): CollectionModelEntityModelUserGroupEntityEmbedded {
  return CollectionModelEntityModelUserGroupEntityEmbeddedFromJSONTyped(json, false);
}

export function CollectionModelEntityModelUserGroupEntityEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CollectionModelEntityModelUserGroupEntityEmbedded {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userGroupEntities: !exists(json, 'userGroupEntities')
      ? undefined
      : (json['userGroupEntities'] as Array<any>).map(EntityModelUserGroupEntityFromJSON),
  };
}

export function CollectionModelEntityModelUserGroupEntityEmbeddedToJSON(
  value?: CollectionModelEntityModelUserGroupEntityEmbedded | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userGroupEntities:
      value.userGroupEntities === undefined
        ? undefined
        : (value.userGroupEntities as Array<any>).map(EntityModelUserGroupEntityToJSON),
  };
}
