/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  UserEntityResponse,
  UserEntityResponseFromJSON,
  UserEntityResponseFromJSONTyped,
  UserEntityResponseToJSON,
} from './UserEntityResponse';

/**
 *
 * @export
 * @interface CollectionModelUserEntityEmbedded
 */
export interface CollectionModelUserEntityEmbedded {
  /**
   *
   * @type {Array<UserEntityResponse>}
   * @memberof CollectionModelUserEntityEmbedded
   */
  userEntities?: Array<UserEntityResponse>;
}

export function CollectionModelUserEntityEmbeddedFromJSON(json: any): CollectionModelUserEntityEmbedded {
  return CollectionModelUserEntityEmbeddedFromJSONTyped(json, false);
}

export function CollectionModelUserEntityEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CollectionModelUserEntityEmbedded {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userEntities: !exists(json, 'userEntities')
      ? undefined
      : (json['userEntities'] as Array<any>).map(UserEntityResponseFromJSON),
  };
}

export function CollectionModelUserEntityEmbeddedToJSON(value?: CollectionModelUserEntityEmbedded | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userEntities:
      value.userEntities === undefined ? undefined : (value.userEntities as Array<any>).map(UserEntityResponseToJSON),
  };
}
