/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { Link, LinkFromJSON, LinkFromJSONTyped, LinkToJSON } from './Link';
import {
  PagedModelEntityModelVideoEntityEmbedded,
  PagedModelEntityModelVideoEntityEmbeddedFromJSON,
  PagedModelEntityModelVideoEntityEmbeddedFromJSONTyped,
  PagedModelEntityModelVideoEntityEmbeddedToJSON,
} from './PagedModelEntityModelVideoEntityEmbedded';

/**
 *
 * @export
 * @interface CollectionModelEntityModelVideoEntity
 */
export interface CollectionModelEntityModelVideoEntity {
  /**
   *
   * @type {PagedModelEntityModelVideoEntityEmbedded}
   * @memberof CollectionModelEntityModelVideoEntity
   */
  embedded?: PagedModelEntityModelVideoEntityEmbedded;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof CollectionModelEntityModelVideoEntity
   */
  links?: { [key: string]: Link };
}

export function CollectionModelEntityModelVideoEntityFromJSON(json: any): CollectionModelEntityModelVideoEntity {
  return CollectionModelEntityModelVideoEntityFromJSONTyped(json, false);
}

export function CollectionModelEntityModelVideoEntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CollectionModelEntityModelVideoEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    embedded: !exists(json, '_embedded')
      ? undefined
      : PagedModelEntityModelVideoEntityEmbeddedFromJSON(json['_embedded']),
    links: !exists(json, '_links') ? undefined : mapValues(json['_links'], LinkFromJSON),
  };
}

export function CollectionModelEntityModelVideoEntityToJSON(value?: CollectionModelEntityModelVideoEntity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    _embedded: PagedModelEntityModelVideoEntityEmbeddedToJSON(value.embedded),
    _links: value.links === undefined ? undefined : mapValues(value.links, LinkToJSON),
  };
}
