/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  CollectionModelAuthorityEntityEmbedded,
  CollectionModelAuthorityEntityEmbeddedFromJSON,
  CollectionModelAuthorityEntityEmbeddedFromJSONTyped,
  CollectionModelAuthorityEntityEmbeddedToJSON,
} from './CollectionModelAuthorityEntityEmbedded';
import { Link, LinkFromJSON, LinkFromJSONTyped, LinkToJSON } from './Link';

/**
 *
 * @export
 * @interface CollectionModelAuthorityEntity
 */
export interface CollectionModelAuthorityEntity {
  /**
   *
   * @type {CollectionModelAuthorityEntityEmbedded}
   * @memberof CollectionModelAuthorityEntity
   */
  embedded?: CollectionModelAuthorityEntityEmbedded;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof CollectionModelAuthorityEntity
   */
  links?: { [key: string]: Link };
}

export function CollectionModelAuthorityEntityFromJSON(json: any): CollectionModelAuthorityEntity {
  return CollectionModelAuthorityEntityFromJSONTyped(json, false);
}

export function CollectionModelAuthorityEntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CollectionModelAuthorityEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    embedded: !exists(json, '_embedded')
      ? undefined
      : CollectionModelAuthorityEntityEmbeddedFromJSON(json['_embedded']),
    links: !exists(json, '_links') ? undefined : mapValues(json['_links'], LinkFromJSON),
  };
}

export function CollectionModelAuthorityEntityToJSON(value?: CollectionModelAuthorityEntity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    _embedded: CollectionModelAuthorityEntityEmbeddedToJSON(value.embedded),
    _links: value.links === undefined ? undefined : mapValues(value.links, LinkToJSON),
  };
}
