/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { Link, LinkFromJSON, LinkFromJSONTyped, LinkToJSON } from './Link';
import {
  PagedModelEntityModelUserEntityEmbedded,
  PagedModelEntityModelUserEntityEmbeddedFromJSON,
  PagedModelEntityModelUserEntityEmbeddedFromJSONTyped,
  PagedModelEntityModelUserEntityEmbeddedToJSON,
} from './PagedModelEntityModelUserEntityEmbedded';

/**
 *
 * @export
 * @interface CollectionModelEntityModelUserEntity
 */
export interface CollectionModelEntityModelUserEntity {
  /**
   *
   * @type {PagedModelEntityModelUserEntityEmbedded}
   * @memberof CollectionModelEntityModelUserEntity
   */
  embedded?: PagedModelEntityModelUserEntityEmbedded;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof CollectionModelEntityModelUserEntity
   */
  links?: { [key: string]: Link };
}

export function CollectionModelEntityModelUserEntityFromJSON(json: any): CollectionModelEntityModelUserEntity {
  return CollectionModelEntityModelUserEntityFromJSONTyped(json, false);
}

export function CollectionModelEntityModelUserEntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CollectionModelEntityModelUserEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    embedded: !exists(json, '_embedded')
      ? undefined
      : PagedModelEntityModelUserEntityEmbeddedFromJSON(json['_embedded']),
    links: !exists(json, '_links') ? undefined : mapValues(json['_links'], LinkFromJSON),
  };
}

export function CollectionModelEntityModelUserEntityToJSON(value?: CollectionModelEntityModelUserEntity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    _embedded: PagedModelEntityModelUserEntityEmbeddedToJSON(value.embedded),
    _links: value.links === undefined ? undefined : mapValues(value.links, LinkToJSON),
  };
}
