/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { UserView, UserViewFromJSON, UserViewFromJSONTyped, UserViewToJSON } from './UserView';

/**
 *
 * @export
 * @interface CommonAuthResponse
 */
export interface CommonAuthResponse {
  /**
   *
   * @type {UserView}
   * @memberof CommonAuthResponse
   */
  user?: UserView;
  /**
   *
   * @type {string}
   * @memberof CommonAuthResponse
   */
  errorMessage?: string;
}

export function CommonAuthResponseFromJSON(json: any): CommonAuthResponse {
  return CommonAuthResponseFromJSONTyped(json, false);
}

export function CommonAuthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonAuthResponse {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    user: !exists(json, 'user') ? undefined : UserViewFromJSON(json['user']),
    errorMessage: !exists(json, 'errorMessage') ? undefined : json['errorMessage'],
  };
}

export function CommonAuthResponseToJSON(value?: CommonAuthResponse | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    user: UserViewToJSON(value.user),
    errorMessage: value.errorMessage,
  };
}
