/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {
  /**
   *
   * @type {string}
   * @memberof CreateUserDto
   */
  username: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserDto
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserDto
   */
  passwordRepeat: string;
  /**
   *
   * @type {string}
   * @memberof CreateUserDto
   */
  name?: string;
  /**
   *
   * @type {Set<string>}
   * @memberof CreateUserDto
   */
  authorities?: Set<string>;
  /**
   *
   * @type {string}
   * @memberof CreateUserDto
   */
  group?: string;
}

export function CreateUserDtoFromJSON(json: any): CreateUserDto {
  return CreateUserDtoFromJSONTyped(json, false);
}

export function CreateUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    username: json['username'],
    password: json['password'],
    passwordRepeat: json['passwordRepeat'],
    name: !exists(json, 'name') ? undefined : json['name'],
    authorities: !exists(json, 'authorities') ? undefined : json['authorities'],
    group: !exists(json, 'group') ? undefined : json['group'],
  };
}

export function CreateUserDtoToJSON(value?: CreateUserDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    username: value.username,
    password: value.password,
    passwordRepeat: value.passwordRepeat,
    name: value.name,
    authorities: value.authorities,
    group: value.group,
  };
}
