/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { Link, LinkFromJSON, LinkFromJSONTyped, LinkToJSON } from './Link';
import { UserEntity, UserEntityFromJSON, UserEntityFromJSONTyped, UserEntityToJSON } from './UserEntity';

/**
 *
 * @export
 * @interface EntityModelUserGroupEntity
 */
export interface EntityModelUserGroupEntity {
  /**
   *
   * @type {string}
   * @memberof EntityModelUserGroupEntity
   */
  name: string;
  /**
   *
   * @type {Array<UserEntity>}
   * @memberof EntityModelUserGroupEntity
   */
  users: Array<UserEntity>;
  /**
   *
   * @type {number}
   * @memberof EntityModelUserGroupEntity
   */
  id?: number;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof EntityModelUserGroupEntity
   */
  links?: { [key: string]: Link };
}

export function EntityModelUserGroupEntityFromJSON(json: any): EntityModelUserGroupEntity {
  return EntityModelUserGroupEntityFromJSONTyped(json, false);
}

export function EntityModelUserGroupEntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EntityModelUserGroupEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    users: (json['users'] as Array<any>).map(UserEntityFromJSON),
    id: !exists(json, 'id') ? undefined : json['id'],
    links: !exists(json, '_links') ? undefined : mapValues(json['_links'], LinkFromJSON),
  };
}

export function EntityModelUserGroupEntityToJSON(value?: EntityModelUserGroupEntity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    users: (value.users as Array<any>).map(UserEntityToJSON),
    id: value.id,
    _links: value.links === undefined ? undefined : mapValues(value.links, LinkToJSON),
  };
}
