/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  AbstractJsonSchemaPropertyObject,
  AbstractJsonSchemaPropertyObjectFromJSON,
  AbstractJsonSchemaPropertyObjectFromJSONTyped,
  AbstractJsonSchemaPropertyObjectToJSON,
} from './AbstractJsonSchemaPropertyObject';

/**
 *
 * @export
 * @interface Item
 */
export interface Item {
  /**
   *
   * @type {string}
   * @memberof Item
   */
  type?: string;
  /**
   *
   * @type {{ [key: string]: AbstractJsonSchemaPropertyObject; }}
   * @memberof Item
   */
  properties?: { [key: string]: AbstractJsonSchemaPropertyObject };
  /**
   *
   * @type {Array<string>}
   * @memberof Item
   */
  requiredProperties?: Array<string>;
}

export function ItemFromJSON(json: any): Item {
  return ItemFromJSONTyped(json, false);
}

export function ItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Item {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    type: !exists(json, 'type') ? undefined : json['type'],
    properties: !exists(json, 'properties')
      ? undefined
      : mapValues(json['properties'], AbstractJsonSchemaPropertyObjectFromJSON),
    requiredProperties: !exists(json, 'requiredProperties') ? undefined : json['requiredProperties'],
  };
}

export function ItemToJSON(value?: Item | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    type: value.type,
    properties:
      value.properties === undefined ? undefined : mapValues(value.properties, AbstractJsonSchemaPropertyObjectToJSON),
    requiredProperties: value.requiredProperties,
  };
}
