/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { Link, LinkFromJSON, LinkFromJSONTyped, LinkToJSON } from './Link';
import { PageMetadata, PageMetadataFromJSON, PageMetadataFromJSONTyped, PageMetadataToJSON } from './PageMetadata';
import {
  PagedModelEntityModelAuthorityEntityEmbedded,
  PagedModelEntityModelAuthorityEntityEmbeddedFromJSON,
  PagedModelEntityModelAuthorityEntityEmbeddedFromJSONTyped,
  PagedModelEntityModelAuthorityEntityEmbeddedToJSON,
} from './PagedModelEntityModelAuthorityEntityEmbedded';

/**
 *
 * @export
 * @interface PagedModelEntityModelAuthorityEntity
 */
export interface PagedModelEntityModelAuthorityEntity {
  /**
   *
   * @type {PagedModelEntityModelAuthorityEntityEmbedded}
   * @memberof PagedModelEntityModelAuthorityEntity
   */
  embedded?: PagedModelEntityModelAuthorityEntityEmbedded;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof PagedModelEntityModelAuthorityEntity
   */
  links?: { [key: string]: Link };
  /**
   *
   * @type {PageMetadata}
   * @memberof PagedModelEntityModelAuthorityEntity
   */
  page?: PageMetadata;
}

export function PagedModelEntityModelAuthorityEntityFromJSON(json: any): PagedModelEntityModelAuthorityEntity {
  return PagedModelEntityModelAuthorityEntityFromJSONTyped(json, false);
}

export function PagedModelEntityModelAuthorityEntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PagedModelEntityModelAuthorityEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    embedded: !exists(json, '_embedded')
      ? undefined
      : PagedModelEntityModelAuthorityEntityEmbeddedFromJSON(json['_embedded']),
    links: !exists(json, '_links') ? undefined : mapValues(json['_links'], LinkFromJSON),
    page: !exists(json, 'page') ? undefined : PageMetadataFromJSON(json['page']),
  };
}

export function PagedModelEntityModelAuthorityEntityToJSON(value?: PagedModelEntityModelAuthorityEntity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    _embedded: PagedModelEntityModelAuthorityEntityEmbeddedToJSON(value.embedded),
    _links: value.links === undefined ? undefined : mapValues(value.links, LinkToJSON),
    page: PageMetadataToJSON(value.page),
  };
}
