/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { Link, LinkFromJSON, LinkFromJSONTyped, LinkToJSON } from './Link';
import { PageMetadata, PageMetadataFromJSON, PageMetadataFromJSONTyped, PageMetadataToJSON } from './PageMetadata';
import {
  PagedModelEntityModelUserEntityEmbedded,
  PagedModelEntityModelUserEntityEmbeddedFromJSON,
  PagedModelEntityModelUserEntityEmbeddedFromJSONTyped,
  PagedModelEntityModelUserEntityEmbeddedToJSON,
} from './PagedModelEntityModelUserEntityEmbedded';

/**
 *
 * @export
 * @interface PagedModelEntityModelUserEntity
 */
export interface PagedModelEntityModelUserEntity {
  /**
   *
   * @type {PagedModelEntityModelUserEntityEmbedded}
   * @memberof PagedModelEntityModelUserEntity
   */
  embedded?: PagedModelEntityModelUserEntityEmbedded;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof PagedModelEntityModelUserEntity
   */
  links?: { [key: string]: Link };
  /**
   *
   * @type {PageMetadata}
   * @memberof PagedModelEntityModelUserEntity
   */
  page?: PageMetadata;
}

export function PagedModelEntityModelUserEntityFromJSON(json: any): PagedModelEntityModelUserEntity {
  return PagedModelEntityModelUserEntityFromJSONTyped(json, false);
}

export function PagedModelEntityModelUserEntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PagedModelEntityModelUserEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    embedded: !exists(json, '_embedded')
      ? undefined
      : PagedModelEntityModelUserEntityEmbeddedFromJSON(json['_embedded']),
    links: !exists(json, '_links') ? undefined : mapValues(json['_links'], LinkFromJSON),
    page: !exists(json, 'page') ? undefined : PageMetadataFromJSON(json['page']),
  };
}

export function PagedModelEntityModelUserEntityToJSON(value?: PagedModelEntityModelUserEntity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    _embedded: PagedModelEntityModelUserEntityEmbeddedToJSON(value.embedded),
    _links: value.links === undefined ? undefined : mapValues(value.links, LinkToJSON),
    page: PageMetadataToJSON(value.page),
  };
}
