/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  EntityModelAuthorityEntity,
  EntityModelAuthorityEntityFromJSON,
  EntityModelAuthorityEntityFromJSONTyped,
  EntityModelAuthorityEntityToJSON,
} from './EntityModelAuthorityEntity';

/**
 *
 * @export
 * @interface PagedModelEntityModelAuthorityEntityEmbedded
 */
export interface PagedModelEntityModelAuthorityEntityEmbedded {
  /**
   *
   * @type {Array<EntityModelAuthorityEntity>}
   * @memberof PagedModelEntityModelAuthorityEntityEmbedded
   */
  authorityEntities?: Array<EntityModelAuthorityEntity>;
}

export function PagedModelEntityModelAuthorityEntityEmbeddedFromJSON(
  json: any,
): PagedModelEntityModelAuthorityEntityEmbedded {
  return PagedModelEntityModelAuthorityEntityEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelAuthorityEntityEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PagedModelEntityModelAuthorityEntityEmbedded {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    authorityEntities: !exists(json, 'authorityEntities')
      ? undefined
      : (json['authorityEntities'] as Array<any>).map(EntityModelAuthorityEntityFromJSON),
  };
}

export function PagedModelEntityModelAuthorityEntityEmbeddedToJSON(
  value?: PagedModelEntityModelAuthorityEntityEmbedded | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    authorityEntities:
      value.authorityEntities === undefined
        ? undefined
        : (value.authorityEntities as Array<any>).map(EntityModelAuthorityEntityToJSON),
  };
}
