/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import { Link, LinkFromJSON, LinkFromJSONTyped, LinkToJSON } from './Link';
import { PageMetadata, PageMetadataFromJSON, PageMetadataFromJSONTyped, PageMetadataToJSON } from './PageMetadata';
import {
  PagedModelEntityModelVideoEntityEmbedded,
  PagedModelEntityModelVideoEntityEmbeddedFromJSON,
  PagedModelEntityModelVideoEntityEmbeddedFromJSONTyped,
  PagedModelEntityModelVideoEntityEmbeddedToJSON,
} from './PagedModelEntityModelVideoEntityEmbedded';

/**
 *
 * @export
 * @interface PagedModelEntityModelVideoEntity
 */
export interface PagedModelEntityModelVideoEntity {
  /**
   *
   * @type {PagedModelEntityModelVideoEntityEmbedded}
   * @memberof PagedModelEntityModelVideoEntity
   */
  embedded?: PagedModelEntityModelVideoEntityEmbedded;
  /**
   *
   * @type {{ [key: string]: Link; }}
   * @memberof PagedModelEntityModelVideoEntity
   */
  links?: { [key: string]: Link };
  /**
   *
   * @type {PageMetadata}
   * @memberof PagedModelEntityModelVideoEntity
   */
  page?: PageMetadata;
}

export function PagedModelEntityModelVideoEntityFromJSON(json: any): PagedModelEntityModelVideoEntity {
  return PagedModelEntityModelVideoEntityFromJSONTyped(json, false);
}

export function PagedModelEntityModelVideoEntityFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PagedModelEntityModelVideoEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    embedded: !exists(json, '_embedded')
      ? undefined
      : PagedModelEntityModelVideoEntityEmbeddedFromJSON(json['_embedded']),
    links: !exists(json, '_links') ? undefined : mapValues(json['_links'], LinkFromJSON),
    page: !exists(json, 'page') ? undefined : PageMetadataFromJSON(json['page']),
  };
}

export function PagedModelEntityModelVideoEntityToJSON(value?: PagedModelEntityModelVideoEntity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    _embedded: PagedModelEntityModelVideoEntityEmbeddedToJSON(value.embedded),
    _links: value.links === undefined ? undefined : mapValues(value.links, LinkToJSON),
    page: PageMetadataToJSON(value.page),
  };
}
