/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  EntityModelUserEntity,
  EntityModelUserEntityFromJSON,
  EntityModelUserEntityFromJSONTyped,
  EntityModelUserEntityToJSON,
} from './EntityModelUserEntity';

/**
 *
 * @export
 * @interface PagedModelEntityModelUserEntityEmbedded
 */
export interface PagedModelEntityModelUserEntityEmbedded {
  /**
   *
   * @type {Array<EntityModelUserEntity>}
   * @memberof PagedModelEntityModelUserEntityEmbedded
   */
  userEntities?: Array<EntityModelUserEntity>;
}

export function PagedModelEntityModelUserEntityEmbeddedFromJSON(json: any): PagedModelEntityModelUserEntityEmbedded {
  return PagedModelEntityModelUserEntityEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelUserEntityEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PagedModelEntityModelUserEntityEmbedded {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    userEntities: !exists(json, 'userEntities')
      ? undefined
      : (json['userEntities'] as Array<any>).map(EntityModelUserEntityFromJSON),
  };
}

export function PagedModelEntityModelUserEntityEmbeddedToJSON(
  value?: PagedModelEntityModelUserEntityEmbedded | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    userEntities:
      value.userEntities === undefined
        ? undefined
        : (value.userEntities as Array<any>).map(EntityModelUserEntityToJSON),
  };
}
