/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  EntityModelVideoEntity,
  EntityModelVideoEntityFromJSON,
  EntityModelVideoEntityFromJSONTyped,
  EntityModelVideoEntityToJSON,
} from './EntityModelVideoEntity';

/**
 *
 * @export
 * @interface PagedModelEntityModelVideoEntityEmbedded
 */
export interface PagedModelEntityModelVideoEntityEmbedded {
  /**
   *
   * @type {Array<EntityModelVideoEntity>}
   * @memberof PagedModelEntityModelVideoEntityEmbedded
   */
  videoEntities?: Array<EntityModelVideoEntity>;
}

export function PagedModelEntityModelVideoEntityEmbeddedFromJSON(json: any): PagedModelEntityModelVideoEntityEmbedded {
  return PagedModelEntityModelVideoEntityEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelVideoEntityEmbeddedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PagedModelEntityModelVideoEntityEmbedded {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    videoEntities: !exists(json, 'videoEntities')
      ? undefined
      : (json['videoEntities'] as Array<any>).map(EntityModelVideoEntityFromJSON),
  };
}

export function PagedModelEntityModelVideoEntityEmbeddedToJSON(
  value?: PagedModelEntityModelVideoEntityEmbedded | null,
): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    videoEntities:
      value.videoEntities === undefined
        ? undefined
        : (value.videoEntities as Array<any>).map(EntityModelVideoEntityToJSON),
  };
}
