/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
  AuthorityEntity,
  AuthorityEntityFromJSON,
  AuthorityEntityFromJSONTyped,
  AuthorityEntityToJSON,
} from './AuthorityEntity';
import {
  UserGroupEntity,
  UserGroupEntityFromJSON,
  UserGroupEntityFromJSONTyped,
  UserGroupEntityToJSON,
} from './UserGroupEntity';
import { VideoEntity, VideoEntityFromJSON, VideoEntityFromJSONTyped, VideoEntityToJSON } from './VideoEntity';

/**
 *
 * @export
 * @interface UserEntity
 */
export interface UserEntity {
  /**
   *
   * @type {string}
   * @memberof UserEntity
   */
  username: string;
  /**
   *
   * @type {boolean}
   * @memberof UserEntity
   */
  enabled: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UserEntity
   */
  accountNonExpired: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UserEntity
   */
  credentialsNonExpired: boolean;
  /**
   *
   * @type {boolean}
   * @memberof UserEntity
   */
  accountNonLocked: boolean;
  /**
   *
   * @type {Set<AuthorityEntity>}
   * @memberof UserEntity
   */
  authorities: Set<AuthorityEntity>;
  /**
   *
   * @type {UserGroupEntity}
   * @memberof UserEntity
   */
  group?: UserGroupEntity;
  /**
   *
   * @type {string}
   * @memberof UserEntity
   */
  name: string;
  /**
   *
   * @type {Array<VideoEntity>}
   * @memberof UserEntity
   */
  videos: Array<VideoEntity>;
  /**
   *
   * @type {number}
   * @memberof UserEntity
   */
  id?: number;
}

export function UserEntityFromJSON(json: any): UserEntity {
  return UserEntityFromJSONTyped(json, false);
}

export function UserEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserEntity {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    username: json['username'],
    enabled: json['enabled'],
    accountNonExpired: json['accountNonExpired'],
    credentialsNonExpired: json['credentialsNonExpired'],
    accountNonLocked: json['accountNonLocked'],
    authorities: new Set((json['authorities'] as Array<any>).map(AuthorityEntityFromJSON)),
    group: !exists(json, 'group') ? undefined : UserGroupEntityFromJSON(json['group']),
    name: json['name'],
    videos: (json['videos'] as Array<any>).map(VideoEntityFromJSON),
    id: !exists(json, 'id') ? undefined : json['id'],
  };
}

export function UserEntityToJSON(value?: UserEntity | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    username: value.username,
    enabled: value.enabled,
    accountNonExpired: value.accountNonExpired,
    credentialsNonExpired: value.credentialsNonExpired,
    accountNonLocked: value.accountNonLocked,
    authorities: Array.from(value.authorities as Set<any>).map(AuthorityEntityToJSON),
    group: UserGroupEntityToJSON(value.group),
    name: value.name,
    videos: (value.videos as Array<any>).map(VideoEntityToJSON),
    id: value.id,
  };
}
