/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserView
 */
export interface UserView {
  /**
   *
   * @type {string}
   * @memberof UserView
   */
  username: string;
}

export function UserViewFromJSON(json: any): UserView {
  return UserViewFromJSONTyped(json, false);
}

export function UserViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserView {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    username: json['username'],
  };
}

export function UserViewToJSON(value?: UserView | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    username: value.username,
  };
}
