/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserGroupEntityRequestBody
 */
export interface UserGroupEntityRequestBody {
  /**
   *
   * @type {string}
   * @memberof UserGroupEntityRequestBody
   */
  name: string;
  /**
   *
   * @type {Array<string>}
   * @memberof UserGroupEntityRequestBody
   */
  users: Array<string>;
  /**
   *
   * @type {number}
   * @memberof UserGroupEntityRequestBody
   */
  id?: number;
}

export function UserGroupEntityRequestBodyFromJSON(json: any): UserGroupEntityRequestBody {
  return UserGroupEntityRequestBodyFromJSONTyped(json, false);
}

export function UserGroupEntityRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserGroupEntityRequestBody {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    users: json['users'],
    id: !exists(json, 'id') ? undefined : json['id'],
  };
}

export function UserGroupEntityRequestBodyToJSON(value?: UserGroupEntityRequestBody | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    users: value.users,
    id: value.id,
  };
}
